### ISSUE TITLE
Check why 'HCL Commerce' detection is not working

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5733]
Example site where detection is not working - https://www.dillards.com/?facet=dil_shipinternational:Y

Current detection - 
```
  "HCL Commerce": {
    "cats": [
      6
    ],
    "html": "<(?:a|link|script)[^>]*(?:href|src)=\".*(?:/wcsstore/|webapp\\/wcs)",
    "icon": "HCL Commerce.svg",
    "implies": "Java",
    "pricing": [
      "poa"
    ],
    "saas": true,
    "url": "/wcs/",
    "website": "https://www.hcltechsw.com/products/commerce"
  },
```
This site has links like '/webapp/wcs/stores/servlet/LogonForm' but Chrome extension is not detecting 'HCL Commerce' on this site.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , interesting case. Although links are visible in the browser, nothing was visible locally.
Although with the current version everything works if you go, for example, to the page [example_page_same_domain](https://www.dillards.com/webapp/wcs/stores/servlet/LogonForm?storeId=301&langId=-1&catalogId=301). 
I think when this technology was added earlier, there was the same problem that it was impossible to define this technology in the home page in some examples, and therefore the  `url` attribute was added.
I think it can be removed so that there are no false positive results. ` "url": "/wps/",`
On other pages I noticed this code inside the tjga script.
![image](https://user-images.githubusercontent.com/3456008/158236778-149e490c-5c5e-4687-81f3-051ab798c426.png)
I tried to take it through `scripts` attribute and the technology began to be determined  on the home page.
