### ISSUE TITLE
False positives for BRT detection

### ISSUE THREAD

**Issue by basvanschaik** [wappalyzer/wappalyzer#6100]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
The current detection rule for BRT is \bBRT\b which easily leads to false positives. There are not that many sites that use this "Italian-based logistics service provider", and there three letters are to weak and appear to often to state 100% confidence of detection.

**To Reproduce**
If you do this:
    node /home/maddox/wappalyzer/src/drivers/npm/cli.js  https://www.geobasisregistraties.nl

If will wrongly detect BRT due to this meta tag:

   <meta name="[description]()" content="[Op deze website vindt u alle officiële informatie, kennisdocumenten, nieuwsitems en evenementen rondom de geobasisregistraties (BAG, BRT, BGT, BRK en BRO) en de Doorontwikkeling in Samenhang van de Geobasisregistraties (DiS Geo).]()"/>

**Expected behavior**
BRT should not be detected

**Comment by AliasIO** [comment]
Thanks. It's actually because it appears in the text here:

<img width="828" alt="Screen Shot 2022-04-15 at 9 53 20 am" src="https://user-images.githubusercontent.com/77259/163494838-3632a433-b8a5-49ab-863d-e5710c6455e2.png">
There is a bug though, it's should only identify shipping carriers when an ecommerce platform is detected, which should reduce false positives. I'll look into that.
